[package]
name = "tetrs"
version = "0.1.0"
authors = ["wolfgang <wolfgang@wolfgangdeutsch.work>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.7.7"
raylib = "0.9.1"