pub mod brick_drop_test;
pub mod horizontal_movement_test;
pub mod vertical_collision_test;
pub mod horizontal_collision_test;
pub mod sequential_brick_provider_test;
pub mod testable_game_factory_test;
pub mod rotation_with_collision_test;
pub mod all_brick_rotations_test;
pub mod vanishing_lines_test;